export const ActionType = {
    INIT: 'INIT',
    SET_OBJECT: 'SET_OBJECT',
    ADD_OBJECT: 'ADD_OBECT',
    UPDATE_OBECT: 'UPDATE_OBJECT',
    DELETE_OBJECT: 'DELETE_OBJECT',

    SET_MODAL: 'SET_MODAL',

    ADD_ERROR_LISTENER: 'ADD_ERROR_LISTENER',
    REMOVE_ERROR_LISTENER: 'REMOVE_ERROR_LISTENER',

    ADD_ERROR: 'ADD_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR',
};
